// Client exports
export {
  api,
  setToken,
  clearToken,
  ApiError,
  createApiClient,
  createTokenManager,
} from "./client";
export type { ApiClient } from "./client";
export {
  API_CATALOG_SCHEMA_VERSION,
  APICatalogContractError,
  findBuiltInAPIType,
  isValidAPIType,
  isValidCustomAPIType,
  parseAPICatalog,
} from "./api-catalog";
export type { APICatalog, APICatalogEntry } from "./api-catalog";
export { parseTokenUsageResponse } from "./token-usage-decoders";
export {
  parseCredentialSession,
  parseCredentialSessions,
  parseProvider,
  parseProviders,
  ProviderContractError,
} from "./provider-contract";
export type {
  TokenBreakdownDTO,
  TokenSummaryDTO,
  TokenBucketDTO,
  TokenProviderRankDTO,
  TokenModelRankDTO,
  TokenTimeRangeDTO,
  TokenCoverageDTO,
  TokenDataQualityDTO,
  TokenUsageResponse,
  TokenUsageParams,
} from "./token-usage-types";
export { createDebugCaptureApi } from "./debug-capture";
export type { DebugCaptureApi } from "./debug-capture";
export type {
  CaptureCompletion,
  CaptureCredentialPhase,
  CaptureLifecycleState,
  CaptureProtocol,
  CaptureSelectionMode,
  CaptureSelectionSource,
  CaptureSnapshotState,
  CaptureSourceCompletion,
  CaptureTerminationReason,
  CreateDebugCaptureExportRequest,
  DebugCaptureBlobPreview,
  DebugCaptureDownloadGrant,
  DebugCaptureFailureClass,
  DebugCaptureFailureCode,
  DebugCaptureFailureFact,
  DebugCaptureFailureObservation,
  DebugCaptureFailurePeer,
  DebugCaptureFailureSite,
  DebugCaptureHeaders,
  DebugCaptureHTTPExchangeDetail,
  DebugCaptureMessageSnapshot,
  DebugCaptureProcessMemoryStatus,
  DebugCaptureProviderIdentity,
  DebugCaptureProviderSnapshot,
  DebugCaptureRecordDetail,
  DebugCaptureRecordSummary,
  DebugCaptureRecordsPage,
  DebugCaptureRecordsQuery,
  DebugCaptureSessionInfo,
  DebugCaptureSessionStatus,
  DebugCaptureState,
  DebugCaptureStatus,
  DebugCaptureTraceEntry,
  DebugCaptureTraceSummary,
  DebugCaptureWebSocketCloseSnapshot,
  DebugCaptureWebSocketExchangeDetail,
  StartDebugCaptureRequest,
} from "./debug-capture-types";

// Type exports
export type {
  // Enum types (synced with backend)
  Strategy,
  AuthMode,
  FailoverScope,
  ProviderUsageLimitPolicy,
  ConfigKey,
  ErrorCode,
  ApiErrorDetails,
  ErrorResponse,
  // Provider types
  BackoffPolicy,
  Provider,
  ProviderAPIType,
  ProviderCredentialSession,
  CredentialSession,
  CredentialSessionKind,
  CredentialSessionAuthState,
  CredentialSubject,
  CredentialSubjectKind,
  CreateCredentialSessionInput,
  RenameCredentialSessionInput,
  ReauthenticateCredentialSessionInput,
  UpdateCredentialSessionInput,
  ProviderAuthStatus,
  ProviderAuthView,
  ProviderInput,
  NewProviderCredentialSessionInput,
  APITypeInput,
  ChatGPTLoginStartResponse,
  ChatGPTLoginStatus,
  ChatGPTLoginStatusResponse,
  CodexAuthTokens,
  CodexAuthDocument,
  RoutingPolicy,
  RoutingPolicyInput,
  RoutingPolicyModelMatchType,
  // Group types
  Group,
  GroupInput,
  // Health & Status types
  HealthState,
  ProviderStatus,
  SystemStatus,
  SystemStatusSummary,
  // Log types
  LegacyRequestLog,
  NormalizedRequestLog,
  RequestLog,
  LogsResponse,
  LogFilter,
  ClientAction,
  CommitSource,
  CompletionState,
  OutcomeTimeSeriesPoint,
  ProviderOutcomeStats,
  RequestEvidence,
  SemanticsVersion,
  ServiceOutcome,
  TerminationActor,
  TerminationReason,
  // Stats types
  StatsPeriod,
  StatsGranularity,
  StatsParams,
  ProviderStats,
  TimeRange,
  StatsResponse,
  // Batch operation types
  BatchAction,
  BatchProviderRequest,
  BatchProviderResult,
  BatchProviderResponse,
  // Config export/import types
  ExportedAPIType,
  ExportedProvider,
  ExportedCredentialAuthState,
  ExportedCredentialSession,
  ExportedCredentialSubject,
  ExportedCredentialUsageSnapshot,
  ExportedCredentialUsageWindow,
  CredentialSessionTransferMode,
  ExportedGroup,
  ExportedInternalErrorRule,
  ExportedRoutingPolicy,
  ExportedConfig,
  FullImportScope,
  ImportMode,
  ImportConfigRequest,
  ChangeCount,
  ImportChanges,
  ImportPreviewResponse,
  AppliedCount,
  ImportedCounts,
  ImportResult,
  ImportScope,
  SelectionImportScope,
  SettingsOnlyImportScope,
} from "./types";
export type {
  ProviderImportCandidate,
  ProviderImportCandidateStatus,
  ProviderImportConflictDetail,
  ProviderImportConflictKind,
  ProviderImportCommitAction,
  ProviderImportCommitItem,
  ProviderImportCreateDefaults,
  ProviderImportCreateCommitItem,
  ProviderImportCommitOutcome,
  ProviderImportCommitRequest,
  ProviderImportCommitResult,
  ProviderImportCommitResultItem,
  ProviderImportCommitSummary,
  ProviderImportIssue,
  ProviderImportMappingNote,
  ProviderImportPreview,
  ProviderImportSummary,
  ProviderImportUpdateCommitItem,
} from "./provider-import-types";

// Interface exports (for testing/mocking)
export type { Storage, HttpClient, ApiClientDeps } from "./interfaces";
export { browserStorage, browserHttpClient } from "./interfaces";

// Context exports
export { APICatalogProvider, ApiProvider } from "./ApiContext";
export { useAPICatalog, useApi } from "./useApi";
